# Use an official Redis image as the base image
FROM redis:6.2-alpine

COPY ./redis.conf /usr/local/etc/redis/redis.conf

# Expose the Redis port
EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
